<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE network [

<!-- DTD for Pete's network -->

<!ELEMENT network ( computer* )>

<!ELEMENT computer ( name, objective, arch, os, services)>

<!ELEMENT name ( #PCDATA )>

<!ELEMENT objective ( #PCDATA )>

<!ELEMENT arch ( #PCDATA )>
<!ATTLIST arch subarch CDATA #REQUIRED>

<!ELEMENT os ( #PCDATA )>
<!ATTLIST os release CDATA #REQUIRED>
<!ATTLIST os nickname CDATA #REQUIRED>
<!ATTLIST os revision CDATA #REQUIRED>

<!ELEMENT services ( service+ )>
<!ATTLIST services network CDATA #REQUIRED>

<!ELEMENT service ( transport, application )>

<!ELEMENT transport ( #PCDATA )>
<!ATTLIST transport port CDATA #REQUIRED>

<!ELEMENT application ( #PCDATA )>

]>

<network>
	<!-- This is the beastly computer that runs the show -->
	<computer>
		<name>Tropism</name>
		<objective>Core server</objective>
		<arch subarch="PentiumPro">i686</arch>
		<os release="stable" nickname="woody" revision="3.0r2">Debian GNU/Linux</os>
		<services network="IP">
			<service>
				<transport port="80">TCP</transport>
				<application>HTTP</application>
			</service>
		</services>
	</computer>
</network>
