=== beentaken/detritus/src/UOW/ITCS201/portfolio/itcs201-portfolio/lab-viva3/network.dtd
<!-- DTD for Pete's network -->

<!ELEMENT network ( computer* )>

<!ELEMENT computer ( name, objective, arch, os, services)>

<!ELEMENT name ( #PCDATA )>

<!ELEMENT objective ( #PCDATA )>

<!ELEMENT arch ( #PCDATA )>

<!ELEMENT os ( name, release, nickname, revision )>

<!ELEMENT release ( #PCDATA )>

<!ELEMENT nickname ( #PCDATA )>

<!ELEMENT revision ( #PCDATA )>

=== beentaken/detritus/src/UOW/ITCS201/portfolio/itcs201-portfolio/lab-viva3/network-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE network SYSTEM "network.dtd">

<network>
	<!-- This is the beastly computer that runs the show -->
	<computer>
		<name>Tropism</name>
		<objective>Core server</objective>
		<arch>i686</arch>
		<os>
			<name>Debian GNU/Linux</name>
			<release>Stable</release>
			<nickname>Woody</nickname>
			<revision>3.0r2</revision>
		</os>
	</computer>
</network>
